GET https://breezy-atom-catmint.glitch.me/

###

GET http://localhost:3000/

###

POST http://localhost:3000/signup
Content-Type: application/json
Accept: *
credentials: true

{
  "email": "kalashinkov2@gmail.com",
  "password": "Test1234",
  "name": "kalashin",
  "phoneNumber" : 1234567890
}
###

POST http://localhost:3000/login
Content-Type: application/json
Accept: *
credentials: true,

{
  "email": "kalashinkov2@gmail.com",
  "password": "Test1234"
}

###

GET http://localhost:8080/logout
Accept: *
credentials: true,


###
GET http://localhost:8080/user
Accept: *
credentials: true