"use strict";
exports.__esModule = true;
exports.router = void 0;
var express_1 = require("express");
var transaction_1 = require("../controllers/transactions/transaction");
var router = express_1.Router();
exports.router = router;
router.post('/transaction/:id', transaction_1.createTransaction);
router.get('/transactions', transaction_1.getAllTransactions);
router.get('/transaction/verify/:id', transaction_1.verifyTransaction);
